# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac98c64592a4d33cafc2bb566c6990eb14915b97efffb677f2cd62a158d7c5afc081888861b89d14365ed3612c6d3321655eb9d4e47b87e4ab50f3f3b8749d5

test:
  secret_key_base: 87c065ac5902be9c33ce5a108c1b413edfb36cdebb096db81b21f522e055b59b4042d23c7697cfb81aaaafe192e1f557d46a06b9a38f679f580aed4a9a2a946e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
